version: "3.9"

services:
  mariadb:
    image: mariadb:11.2.2
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: XShWJZbkijODfSsJfUHw
    ports:
      - 3306:3306
    command: --init-file /docker-entrypoint-initdb.d/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/data:/var/lib/mysql/data/
